# Generated by Django 5.0.6 on 2024-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours_images'),
        ),
    ]
